In [1]:
import torch

# Example 1
tensor1 = torch.rand((3, 3))
print(tensor1)

# Example 2
tensor2 = torch.full((3, 3), 5)
print(tensor2)

# Example 3
result = tensor1 + tensor2
print(result)

tensor([[0.5465, 0.3236, 0.9782],
        [0.4342, 0.2156, 0.1171],
        [0.2669, 0.8060, 0.6470]])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
tensor([[5.5465, 5.3236, 5.9782],
        [5.4342, 5.2156, 5.1171],
        [5.2669, 5.8060, 5.6470]])


In [8]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
reshaped_tensor = tensor.reshape(2, 3)
print(reshaped_tensor.shape)  # Output: (2, 3)
print(reshaped_tensor)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
