In [2]:
import torch

In [7]:
x  = torch.rand(3,2)
y = torch.ones(3,2)
print(x);print(y);


tensor([[0.7981, 0.4814],
        [0.8148, 0.4487],
        [0.2012, 0.2958]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [9]:
torch.where(x>.5, 1.0, 0.0)

tensor([[1., 0.],
        [1., 0.],
        [0., 0.]])

In [10]:
torch.where(x>.5, 1.0, 0.0).mean()

tensor(0.3333)